Adds wait-time arg to registry
simonsobs/ocs pull request #296
Opened 2022-11-02 16:38 UTC by jlashner

Increases default wait time of registry and adds corresponding command line arg.

## Description
Using Matthews script to scan hk files I noticed that the registry was taking up a significant amount of disk space on the SAT1, since the number of fields increases with the number of other agents running on the system. This PR reduces the sleep time in the main loop from 1 sec to 30 sec to mitigate this, and adds the `wait-time` argument that allows users to set it in the sys-config.

## Motivation and Context

Disk space / grafana issues

## How Has This Been Tested?
Tested on my local desktop to make sure it runs.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] Unless I am preparing a release, I have opened this PR onto the `develop` branch.

2022-11-03 19:41 UTC, BrianJKoopman requested changes
This'll definitely reduce the data volume. With long wait times, even the 30 seconds you're using here, I'm worried about missing state changes in the op codes the occur within the wait-time window. What do you think about publishing only on detected op code state changes, then occasionally (whatever the wait-time is set for) publishing everything, even if state hasn't changed?

I know this is time sensitive, so my proposal on the short term is to have the wait-time default to the old value of 1 second. This'll not change behavior for anyone who updates, but still allow you to reduce the data rate on the SAT1 setup. If that's alright with you, I'm fine merging with that one change.

2022-11-04 15:08 UTC, jlashner commented
I think having data published regularly is useful for alerts, so I"m hesitant to only publish data on operation change. This recent PR makes it so ops are published whenever an operation is changed, in addition to once every `wait-time` seconds which defaults to 30. Let me know if that works for you!

2022-11-07 21:50 UTC, BrianJKoopman reviewed
Yeah, perfect, that's what I was trying to ask for. Just one small comment on the log message.

2022-11-07 21:50 UTC, BrianJKoopman commented on ocs/agents/registry/agent.py
> +        self.log.info(addr)
Maybe more appropriately a debug log? If not maybe some more info should be included, like "heartbeat for {addr} published" or similar?

2022-11-07 22:16 UTC, BrianJKoopman approved these changes

2022-11-07 22:39 UTC, merged